Repository CodeForAfrica/TwoopsTrackerUI, pull requests merged in 2022-01, with the labels that each got.

#71 [Hotfix] CMS config loading
  src/pages/admin/index.js
Labels: bug

#72 [Fix] /explore/accounts settings
  src/pages/explore/accounts.js
Labels: bug

#73 [Fix] Show saved query on load
  src/components/Hero/index.js
  src/components/SearchSection/index.js
  src/components/TweetsContainer/index.js
Labels: bug

#74 [Fix] CMS Content Loading
  src/lib/cms.js
Labels: bug

#79 [Fix] Fix Button Hover States
  src/components/SavedSearchDialog/index.js
  src/theme/index.js
Labels: enhancement

#80 [Fix] Add box-shadow to images on Investigate Section
  src/components/InvestigationsPreview/index.js
Labels: enhancement

#87 [Chore]Add support for tweets older than 30 days
  src/components/SearchSection/index.js
  src/lib/index.js
Labels: chore

#83 [Fix] Investigate Card
  src/components/Card/Media.js
  src/components/Card/index.js
  src/components/InvestigationList/index.js
  src/components/InvestigationList/useStyles.js
  src/components/InvestigationsCard/index.js
  src/components/InvestigationsCard/useStyles.js
Labels: bug

#92 [Fix] See More button affordance
  src/components/TweetCard/index.js
  src/components/TweetCard/useStyles.js
Labels: bug

#94 [Fix] Footer
  content/settings/footer.md
  public/images/cfa-logo-white-1.png
  public/images/group-4426.svg
  public/images/twitter-footer.svg
  src/components/Footer/index.js
  src/components/Footer/index.stories.js
  src/components/Footer/useStyles.js
  src/theme/index.js
Labels: bug

#90 [Fix] Monitor disinfo-spreaders Component
  content/pages/index.md
  public/images/Group 40.png
  public/images/group-40-2x.png
  src/components/ExploreTool/index.js
  src/theme/index.js
Labels: bug

#93 [Fix] Tweet card
  .env.sample
  .storybook/main.js
  package.json
  src/components/ExploreTool/index.js
  src/components/Figure/index.js
  src/components/Figure/index.stories.js
  src/components/TweetCard/index.js
  src/components/TweetCard/useStyles.js
  yarn.lock
Labels: bug

#98 Create CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: chore

#82 [FIX] List page spacing
  package.json
  src/components/AccountsList/useStyles.js
  src/components/ContentActions/index.js
  src/components/Lists/index.js
  src/components/Lists/useStyles.js
Labels: bug

#69 [Feature] Add tweet sort
  .github/workflows/codeql-analysis.yml
  src/assets/icons/down-arrow.svg
  src/assets/icons/select-dropdown.svg
  src/assets/icons/sort-down.svg
  src/assets/icons/sort-up.svg
  src/components/ContentActions/index.js
  src/components/Sort/index.js
  src/components/Sort/index.stories.js
  src/components/Sort/useStyles.js
  src/components/TweetSelect/index.js
  src/components/TweetSelect/index.stories.js
  src/components/TweetSelect/useStyles.js
  src/components/TweetsContainer/index.js
  src/components/TweetsContainer/useStyles.js
  src/lib/createChartImage.js
  src/lib/index.js
  src/pages/explore/index.js
  src/utils/getQueryString.js
  yarn.lock
Labels: enhancement
