Repository CodeForAfrica/TwoopsTrackerUI, pull requests merged in 2022-02, with the labels that each got.

#103 [Feature] Accounts lists sorting
  src/components/ContentActions/index.js
  src/components/Lists/index.js
  src/components/Lists/useStyles.js
  src/config/index.js
  src/lib/index.js
  src/pages/account/[[...slug]].js
  src/pages/api/lists/index.js
Labels: enhancement

#104 Search guide
  content/pages/explore.md
  content/settings/footer.md
  src/assets/icons/help-circle.svg
  src/components/SearchGuide/index.js
  src/components/SearchSection/index.js
  src/components/SearchSection/useStyles.js
  src/components/TweetsContainer/index.js
  src/lib/cms.js
  src/pages/api/admin/config.json
  src/pages/explore/index.js
Labels: chore

#108 [Fix] Hide/Show Password Interaction.
  content/pages/auth/login.md
  content/pages/auth/register.md
  content/pages/auth/reset-password.md
  public/images/passwordhide.svg
  src/assets/icons/passwordhide.svg
  src/components/LoginForm/index.js
  src/components/ResetPassword/index.js
  src/components/SignUp/index.js
Labels: enhancement

#110 [Fix] Investigations Page
  src/components/Card/Content.js
  src/components/Card/useStyles.js
  src/components/InvestigationList/index.js
  src/components/InvestigationList/useStyles.js
  src/components/InvestigationsCard/index.js
  src/components/InvestigationsCard/useStyles.js
  src/components/TweetCard/index.js
  src/components/TweetsContainer/index.js
Labels: bug

#112 [Fix] Download Label and File Type Alignment
  src/components/ContentActions/index.js
Labels: bug

#111 [Fix] Disable image optimization
  public/images/group-40-2x.png
  src/assets/images/banner background.png
  src/components/Figure/index.js
  src/components/Footer/useStyles.js
  src/components/Hero/index.js
  src/components/Image/index.js
  src/components/InvestigationsPreview/index.js
  src/components/LoginForm/index.js
  src/components/Navigation/MobileNavigation/index.js
  src/components/Partners/index.js
  src/components/ResetPassword/index.js
  src/components/SignUp/index.js
  src/components/Sort/index.js
  src/components/Upload/index.js
Labels: bug

#107 [Feature]Remove Hardcoded strings to props && cms
  content/components/account.md
  content/components/accountList.md
  content/components/addToList.md
  content/components/search.md
  content/pages/account/update.md
  content/pages/auth/forgot-password.md
  content/pages/auth/login.md
  content/pages/auth/register.md
  content/pages/auth/reset-password.md
  src/components/Account/index.js
  src/components/AccountsList/index.js
  src/components/AddToList/index.js
  src/components/ForgotPassword/index.js
  src/components/ListCard/index.js
  src/components/Lists/index.js
  src/components/LoginForm/index.js
  src/components/ResetPassword/index.js
  src/components/SavedSearchDialog/index.js
  src/components/SearchSection/index.js
  src/components/SignUp/index.js
  src/components/TweetCard/index.js
  src/components/Tweets/index.js
  src/components/TweetsContainer/index.js
  src/components/UserSearch/index.js
  src/components/UserSearchCard/index.js
  src/lib/cms.js
  src/pages/account/[[...slug]].js
  src/pages/account/lists/[listId].js
  src/pages/api/admin/config.json
  src/pages/explore/accounts.js
  src/pages/explore/index.js
Labels: chore

#115 [Chore] Upgrade dependencies
  package.json
  src/components/Upload/index.js
  yarn.lock
Labels: enhancement, chore

#117 [Fix] Chart on md screen
  src/components/Chart/LineScope.js
  src/components/Chart/index.js
Labels: bug

#118 [Fix] Feedback 2
  content/components/search.md
  src/components/Account/index.js
  src/components/AccountsList/index.js
  src/components/Lists/index.js
  src/components/LoginMenu/index.js
  src/components/Navigation/DesktopNavigation/index.js
  src/components/Pagination/index.stories.js
  src/components/Partners/index.js
  src/components/SearchSection/index.js
  src/config/index.js
  src/lib/index.js
  src/pages/account/lists/[listId].js
  src/pages/api/accounts.js
  src/pages/explore/accounts.js
  src/pages/explore/index.js
  src/pages/investigations.js
  src/utils/getQueryString.js
Labels: bug, enhancement

#119 [Feat] Delete user account
  src/components/UserAccount/index.js
  src/pages/api/user/index.js
Labels: enhancement

#120 [HotFix] Account Type Check
  src/components/UpdateProfile/index.js
Labels: bug
